import Navbar from '@/components/Navbar'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'

const robotoMono = Roboto_Mono({
  weight: ['400', '700'],
  display: 'swap',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${robotoMono.className} text-black`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
